version: '3.8'
services:
    mariadb_sistempos:
        image: mariadb:latest
        container_name: mariadb_sistempos
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: user
            MARIADB_PASSWORD: root
            MARIADB_DATABASE: admin
        ports:
            - "3334:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            PMA_HOST: mariadb_sistempos
            PMA_PORT: 3306
            PMA_USER: user
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - mariadb_sistempos
volumes:
    mariadb_data:
